### ISSUE TITLE
Exception while parsing junit results

### ISSUE THREAD

**Issue by x0h01** [samsta/quarantine#7]
After https://github.com/samsta/quarantine/issues/6 resolving plugin aborts execution while parsing test result:
```
ERROR: Publisher org.jenkinsci.plugins.quarantine.QuarantinableJUnitResultArchiver aborted due to exception
java.lang.NoSuchMethodError: org.jenkinsci.plugins.quarantine.QuarantinableJUnitResultArchiver.getTestDataPublishers()Lhudson/util/DescribableList;
  at org.jenkinsci.plugins.quarantine.QuarantinableJUnitResultArchiver.perform(QuarantinableJUnitResultArchiver.java:70)
  at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
  at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
  at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
  at hudson.model.Build$BuildExecution.post2(Build.java:183)
  at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
  at hudson.model.Run.execute(Run.java:1784)
  at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
  at hudson.model.ResourceController.execute(ResourceController.java:89)
  at hudson.model.Executor.run(Executor.java:240)
Finished: FAILURE
```

**Comment by x0h01** [comment]
Maybe the possible reason is jUnit plugin (it was also updated from 1.2-beta-3 to 1.3). Issue disappeared after reverting jUnit and quarantine plugins to their previous versions. But the one, described in https://github.com/samsta/quarantine/issues/6 still exists.

**Comment by samsta** [comment]
thanks, i will have a look at this as soon as i find some time

**Comment by sathishsathyan** [comment]
Facing the same issue. reverting the plugin versions did not help. jenkins version: 1.592

**Comment by stephanebruckert** [comment]
Does anyone have an idea how to fix this? It's a blocker!

**Comment by samsta** [comment]
sorry, i still haven't had time to investigate properly. it is definitely a blocker, we had to remove it from our CI system. i hope i'll get an opportunity in our next cadence

**Comment by stephanebruckert** [comment]
Don't worry, I fixed it today. I will create a pull request tomorrow morning.

**Comment by samsta** [comment]
sounds good, looking forward to it

**Comment by samsta** [comment]
it works on our servers after my latest changes
